-- CreateTable
CREATE TABLE "github_events" (
    "id" BIGINT NOT NULL,
    "type" TEXT,
    "created_at" TIMESTAMP(3),
    "repo_id" INTEGER,
    "repo_name" TEXT,
    "actor_id" INTEGER,
    "actor_login" TEXT,
    "additions" INTEGER,
    "language" TEXT,
    "deletions" INTEGER,
    "extra1" TEXT,
    "action" TEXT,
    "number" INTEGER,
    "commit_id" TEXT,
    "comment_id" INTEGER,
    "org_login" TEXT,
    "org_id" INTEGER,
    "state" TEXT,
    "closed_at" TIMESTAMP(3),
    "comments" INTEGER,
    "pr_merged_at" TIMESTAMP(3),
    "pr_merged" BOOLEAN,
    "pr_changed_files" INTEGER,
    "pr_review_comments" INTEGER,
    "pr_or_issue_id" INTEGER,
    "event_day" TIMESTAMP(3),
    "event_month" TIMESTAMP(3),
    "extra2" TEXT,
    "event_year" INTEGER,
    "push_size" INTEGER,
    "push_distinct_size" INTEGER,
    "creator_user_login" TEXT,
    "creator_user_id" INTEGER,
    "pr_or_issue_created_at" TIMESTAMP(3),

    CONSTRAINT "github_events_pkey" PRIMARY KEY ("id")
);
