-- CreateTable
CREATE TABLE "github_events" (
    "id" SERIAL NOT NULL,
    "type" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL,
    "repo_id" INTEGER NOT NULL,
    "repo_name" TEXT NOT NULL,
    "actor_id" INTEGER NOT NULL,
    "actor_login" TEXT NOT NULL,
    "language" TEXT NOT NULL,
    "additions" INTEGER NOT NULL,
    "deletions" INTEGER NOT NULL,
    "action" TEXT NOT NULL,
    "number" INTEGER NOT NULL,
    "commit_id" TEXT NOT NULL,
    "comment_id" INTEGER NOT NULL,
    "org_login" TEXT NOT NULL,
    "org_id" INTEGER NOT NULL,
    "state" TEXT NOT NULL,
    "closed_at" TIMESTAMP(3) NOT NULL,
    "comments" INTEGER NOT NULL,
    "pr_merged_at" TIMESTAMP(3) NOT NULL,
    "pr_merged" BOOLEAN NOT NULL,
    "pr_changed_files" INTEGER NOT NULL,
    "pr_review_comments" INTEGER NOT NULL,
    "pr_or_issue_id" INTEGER NOT NULL,
    "event_day" TIMESTAMP(3) NOT NULL,
    "event_month" TIMESTAMP(3) NOT NULL,
    "extracolumn" TEXT NOT NULL,
    "event_year" INTEGER NOT NULL,
    "push_size" INTEGER NOT NULL,
    "push_distinct_size" INTEGER NOT NULL,
    "creator_user_login" TEXT NOT NULL,
    "creator_user_id" INTEGER NOT NULL,
    "pr_or_issue_created_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "github_events_pkey" PRIMARY KEY ("id")
);
