-- AlterTable
ALTER TABLE "github_events" ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "type" DROP NOT NULL,
ALTER COLUMN "repo_name" DROP NOT NULL,
ALTER COLUMN "actor_login" DROP NOT NULL,
ALTER COLUMN "language" DROP NOT NULL,
ALTER COLUMN "extra1" DROP NOT NULL,
ALTER COLUMN "action" DROP NOT NULL,
ALTER COLUMN "commit_id" DROP NOT NULL,
ALTER COLUMN "org_login" DROP NOT NULL,
ALTER COLUMN "state" DROP NOT NULL,
ALTER COLUMN "extra2" DROP NOT NULL,
ALTER COLUMN "creator_user_login" DROP NOT NULL;
DROP SEQUENCE "github_events_id_seq";
